project:
  duration:
    - less than 30min
    - 1 hour
    - more than 1 hour
  license:
    - CC Attribution
    - CC Attribution-NoDerivs
    - CC Attribution-NonCommercial-ShareAlike
    - CC Attribution-ShareAlike
    - CC Attribution-NonCommercial
    - CC Attribution-NonCommercial-NoDerivs
  price:
    - "< 10€"
    - "10€ - 20€"
    - "> 20€"
  skills:
    - crafting
    - programming
    - design
    - electronics
    - science
    - fixing
