project:
  duration:
    - less than 30min
    - 1 hour
    - more than 1 hour
  license:
    - CC Attribution
    - CC Attribution-NoDerivs
    - CC Attribution-NonCommercial-ShareAlike
    - CC Attribution-ShareAlike
    - CC Attribution-NonCommercial
    - CC Attribution-NonCommercial-NoDerivs
  price:
    - "< 10€"
    - "10€ - 20€"
    - "> 20€"
  skills:
    - crafting
    - programming
    - design
    - electronics
    - science
    - fixing

media_object:
  styles:
    thumb: '100x100>'
    square: '200x200#'
    medium: '300x300>'
  image_size_in_mb: 4
  image_valid_content_types:
    - 'image/jpeg'
    - 'image/png'
